name: release
on:
  push:
    tags:
      - "*"
  release:
    types: 
      - created
env:
  IMAGE_REPOSITORY: funnyzak/canal-adapter

jobs:
  docker-release:
    name: Publish Docker images
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure docker build context
        uses: docker/setup-buildx-action@v2

      - name: Set reference tags
        id: refs
        run: |
          echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}
          echo ::set-output name=BUILD_DATE::$(date -u +'%Y-%m-%dT%H:%M:%SZ')
      - name: Show available tags vars
        run: |
            echo $SOURCE_NAME
            echo $SOURCE_TAG
        env:
            SOURCE_TAG: ${{ steps.refs.outputs.SOURCE_TAG }}
      - name: Login to Docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push docker images
        uses: docker/build-push-action@v3
        with:
          context: .
          build-args: |
            VCS_REF=${{ github.sha }}
            BUILD_DATE=${{ steps.refs.outputs.BUILD_DATE }}
            CANAL_ADAPTER_VERSION=${{ steps.refs.outputs.SOURCE_TAG }}
          push: true
          tags: |
            ${{ env.IMAGE_REPOSITORY }}:${{ steps.refs.outputs.SOURCE_TAG }}
            ${{ env.IMAGE_REPOSITORY }}:latest
          platforms: linux/amd64

  push-message:
      name: Push message
      runs-on: ubuntu-latest
      needs: [docker-release]
      steps:
        - name: Push message
          uses: funnyzak/pushoo-action@main
          with:
            platforms: ifttt,wecombot,bark
            tokens: ${{ secrets.PUSH_TOKEN }}
            content: |
              # ${{ github.event.repository.name }} Docker Build Success
              ## trigger: ${{ github.event_name }} at ${{ github.event.head_commit.timestamp }}
              ## commit message: ${{ github.event.head_commit.message }}
              ## commit url: ${{ github.event.head_commit.url }}
              ## commit author: ${{ github.event.head_commit.author.name }}
              ## commit email: ${{ github.event.head_commit.author.email }}
              ## commit id: ${{ github.event.head_commit.id }}
            title: |
              ${{ github.repository }} ${{ github.event_name }} Message
            options: '{"bark": { "url": "https://github.com/${{github.repository}}" }}'
            debug: false
